
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: course
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  course-service:
    build: ./course-service
    environment:
      # Configure Spring Boot to connect to the PostgreSQL container.
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/course
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"

  course-ui:
    build: ./course-ui
    ports:
      - "5173:80"

volumes:
  pgdata:
